name: Python application for reading information about added interest from bank statements

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.10.14
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.14
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
