name: Python application for reading information about added interest from bank statements

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
